# Generated by Django 2.2.6 on 2019-10-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmet', models.CharField(max_length=150)),
                ('detay', models.TextField()),
                ('fiyat', models.IntegerField()),
                ('indirim', models.BooleanField()),
                ('pic', models.TextField(max_length=100)),
            ],
        ),
    ]
