# Generated by Django 2.2.6 on 2019-10-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hizmet',
            options={'verbose_name_plural': 'Hizmetler'},
        ),
    ]
